### ISSUE TITLE
T3.2 Replace call to IntrinsicGas

### ISSUE THREAD

**Issue by fkrell** [EspressoSystems/op-leader-election#6]
Parent task #4

**Comment by nyospe** [comment]
The basic aspect of this is simple. It's from the "Gas estimation when creating the batch instead of computing the gas limit client side based on the intrinsic gas in the batcher" bullet point.

See the original calls:
https://github.com/EspressoSystems/op-leader-election/blob/op-leader-election/op-e2e/actions/l2_batcher.go#L210

and (for testing)

https://github.com/EspressoSystems/op-leader-election/blob/op-leader-election/op-e2e/actions/l2_batcher.go#L293

We are replacing this with a check by way of local execution of the target contract over the batch.

Because we don't have a stable address for the target contract, I'm putting in the L2 configuration field for the contract (see https://github.com/EspressoSystems/op-leader-election/issues/15) and using that, alongside the interface, to actually run this call.
